version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carsdb
      - PYTHONPATH=/app
      

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
