services:

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./shared/tempo:/etc
      - ./tempo-data:/var/tempo
    ports:
      - "3200:3200"
    command: ["-config.file=/etc/tempo.yml"]
