services:

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./shared/tempo:/etc
      - ./tempo-data:/var/tempo
    ports:
      - "3200:3200"
    command: ["-config.file=/etc/tempo.yml"]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./shared/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command: 
      - "--web.enable-remote-write-receiver" 
      - "--config.file=/etc/prometheus/prometheus.yml"
  
  loki:
    image: grafana/loki:latest
    volumes:
      - ./shared/loki/chunks:/loki/chunks/
      - ./shared/loki/rules:/loki/rules/
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
  
  promtail:
    image: grafana/promtail:latest
    depends_on:
      - loki
    volumes:
      - ./shared/logs:/var/log
      - ./shared/promtail:/etc/promtail
    command:
      - "-config.file=/etc/promtail/config.yml"
  
  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./shared/alloy:/etc/alloy
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo