version: "3.8"

networks:
  monitoring:
    external: false

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - monitoring
    ports:
      - 9090:9090
    command: 
      - "--web.enable-remote-write-receiver" 
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - monitoring
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_HTTP_TLS_SKIP_VERIFY=true
    ports:
      - 3000:3000
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    networks:
      - monitoring
    ports:
      - 3100:3100
    command:
      - "-config.file=/etc/loki/local-config.yaml"
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    networks:
      - monitoring
    depends_on:
      - loki
    volumes:
      - ./logs:/var/log
      - ./promtail:/etc/promtail
    command:
      - "-config.file=/etc/promtail/config.yml"
  
  shoehub:
    image: aussiearef/shoehub
    container_name: shoehub
    networks:
      - monitoring
    ports:
      - "8020:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LOG_PATH=/app/logs/log.txt
    volumes:
    - ./logs/shoehub:/app/logs:rw
    depends_on:
      - loki
      - prometheus